services:
  - type: web
    name: telegram-trading-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: master
    buildCommand: ""
    startCommand: "./main"
    envVars:
      - key: PORT
        value: ":8080"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: API_AUTH_TOKEN
        value: "fadil123"
      - key: MT4_DATA_PATH
        value: "/opt/render/project/src/mt4-files"
      - key: ATR_PERIOD
        value: "14"
      - key: SL_MULTIPLIER
        value: "1.5"
      - key: TP_MULTIPLIER
        value: "2.0"
      - key: GOLD_DIGITS
        value: "3"
      - key: FOREX_DIGITS
        value: "5"
